// fonts.js
var Roboto_Regular = 
"AAEAAAASAQAABAAgR0RFRrRCsIIAAAC8AAAAYkdQT1O+F8w0AAABHAAAAExHU1VCVoG3iAAAAVwA" +
"AAA+T1MvMsoAAAAAAAGUAAAAYGNtYXAAAABgAAAAsAAAAGR2dERn4M8sAAACcAAAADmhlYWQBAACU" +
"AAABfAAAADZoaGVhBhAAaQAAAXgAAAAkaG10eHwQAAAIAAG4AAAAGGxvY2ED4AQYAAACRAAAAAhtYX" +
"hwAAMAEgAAAkAAAAAgbmFtZZpgGskAAAJkAAABfHBvc3Q5tAA4AAACmAAAACBwcmVwAAAANAAAArQA" +
"AAA7AAEAAAABAACAAAAAAQAAAAEAAQAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA..."; 
// (truncated, huge base64, real file has thousands of characters)

(function (jsPDFAPI) {
  jsPDFAPI.addFileToVFS("Roboto-Regular.ttf", Roboto_Regular);
  jsPDFAPI.addFont("Roboto-Regular.ttf", "Roboto", "normal");
})(jsPDF.API);
